spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URI:file:///${user.home}/config-repo}
          default-label: main
          clone-on-start: true
          force-pull: true
  profiles:
    active: native,git
  security:
    user:
      name: ${CONFIG_USER:admin}
      password: ${CONFIG_PASSWORD:queryHb}

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,busrefresh
  endpoint:
    health:
      show-details: always